### ISSUE TITLE
Working on a method to identify whether node has to run as Server/Client

### ISSUE THREAD

**Issue by sharanaru** [cu-ecen-5013/final-project-sharanaru#1]
Sprint 2 : Make working application code which is capable of detecting if there is a preexisting server on the port and if not act as server, using the previously discussed schemes.
DoD:

 

- [x] Test on development machine (Ubuntu VM)

- [x]  Final test by including it in image and setting it to run on target device, Raspberry Pi.
Works on pi over localhost

Commit:https://github.com/cu-ecen-5013/final-project-sharanaru/commit/f5299684edfcb625dbe130a9da374182fe723816

**Comment by sharanaru** [comment]
Method 1: A defined limit can be set to the maximum number of devices which are allowed in the network. Each device can then send a unique string( maybe a timestamp string) over the port and then expect either the same string back or a acknowledgement from the server(if it exists), if it doesn't they can be set to act as a server. 
Issues: Multiple nodes may be set to act as a server. There needs to be a way to identify if multiple servers exist.

**Comment by sharanaru** [comment]
Method 2: Node can always assume there is a server on the network. Then once the client tries to connect to the server using the connect() call (non-blocking), the returned result and set errno can be used to find if connection was possible or not. Random number of tries can be made before the node decides to act as server in order to avoid creation of multiple servers. 

Issues:  In rare cases, might still cause multiple servers to be setup but in this case, as the project only involves 2-3 devices, chances are very low. 
Speed of connection: Even if a server is present, if the random time makes the node to sleep before the the check can be made, it might lead to invalid cases.

**Comment by sharanaru** [comment]
> Method 2: Node can always assume there is a server on the network. Then once the client tries to connect to the server using the connect() call (non-blocking), the returned result and set errno can be used to find if connection was possible or not. Random number of tries can be made before the node decides to act as server in order to avoid creation of multiple servers.
> 
> Issues: In rare cases, might still cause multiple servers to be setup but in this case, as the project only involves 2-3 devices, chances are very low.
> Speed of connection: Even if a server is present, if the random time makes the node to sleep before the the check can be made, it might lead to invalid cases.

A read/write call can also be used here instead of connect(), if it returns a -1 server setup can be triggered after a random number of times. 
Issues:
As described here: https://stackoverflow.com/questions/1795193/check-connection-open-or-closed-in-c-in-linux
Multiple factors behind a failure in read () call.

**Comment by sharanaru** [comment]
Sprint 2 : Make working application code which is capable of detecting if there is a preexisting server on the port and if not act as server, using the previously discussed schemes. 
DoD:

- [ ] Test on development machine (Ubuntu VM)

- [ ] Final test by including it in image and setting it to run on target device, Raspberry Pi.

**Comment by steveantony5** [comment]
@sharanaru All Dod's must be in first comment. Edit and modify the first comment

Refer: https://docs.google.com/document/d/1nHiCKOrHSQBuZVDpSXKqPFwV5W3lHyvE4heCGnz7ghw/edit referencing step 3.f

**Comment by sharanaru** [comment]
> @sharanaru All Dod's must be in first comment. Edit and modify the first comment
> 
> Refer: https://docs.google.com/document/d/1nHiCKOrHSQBuZVDpSXKqPFwV5W3lHyvE4heCGnz7ghw/edit referencing step 3.f

@steveantony5 I have updated the first comment. Does this satisfy ?

**Comment by sharanaru** [comment]
Implemented strategy: Using a bash script to run netstat utility and find listening ports. If no suitable machine is found server is setup. If a port is found, ip address is then supplied to client

**Comment by steveantony5** [comment]
@sharanaru  please close every issue by linking a commit id

**Comment by sharanaru** [comment]
Sorry just updated it now .

**Comment by sharanaru** [comment]
Problems faced:
+ Tried all 3 ways I mentioned in the comments and I found the present method worked when testing it on just one device. Testing was delayed as it required multiple devices which were in use by other team members.
+ Was hindered by the fact that the WLAN wasn't configured properly and wasn't connecting to the network at boot and as development was done on a VM , couldnt use that to test as it uses the host OS network interface.
+  After testing, found there was no way for the device running the senor fusion application to get the address of the server.
I initially tried to use the nmap utility for this, by pinging all the subnet addresses to find out which ones had the port 9000 open but as this took a longtime as it had do this for all the 255 addresses and I had to also find a way to  just extract the successful information from the output.

**Comment by sharanaru** [comment]
Solution to be tested :  The best way forward would be to initially use UDP to send a message to the broadcast address containing a server IP address once the server has been setup and broadcast until 2 clients send acknowledgements back.
